---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: plex-media-server
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      # renovate: datasource=docker depName=plexinc/pms-docker repository=https://index.docker.io
      tag: 1.40.2.8395-c67dce28e
    ingress:
      enabled: true
      ingressClassName: internal
      url: "plex.${SECRET_DOMAIN}"
    resources:
      requests:
        gpu.intel.com/i915: "1"
        cpu: "1"
      limits:
        gpu.intel.com/i915: "1"
        memory: "4Gi"
