---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: velero-secret
    template:
      engineVersion: v2
      data:
        config.env: |
          [default]
          aws_access_key_id={{ .MINIO_ROOT_USER }}
          aws_secret_access_key={{ .MINIO_ROOT_PASSWORD }}
  dataFrom:
    - extract:
        key: minio
