---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: 10.0.5
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.12.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    configuration:
      backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero-backup
        accessMode: ReadWrite
        credential:
          name: velero-secret
          key: config.env
        config:
          region: casa
          s3ForcePathStyle: true
          s3Url: http://192.168.4.21:9000
          insecureSkipTLSVerify: true

      volumeSnapshotLocation:
      - name: default
        provider: aws
        credential:
          name: velero-secret
          key: config.env
        config:
          region: casa
      features: EnableCSI
      defaultSnapshotMoveData: true
    deployNodeAgent: true
    credentials:
      useSecret: true
      existingSecret: velero-secret
    schedules:
      default:
        disabled: false
        schedule: "0 0 * * *"
        useOwnerReferencesInBackup: false
        paused: false
        template:
          includedNamespaces:
          - default
          includedResources:
          - pvc
          - pv
      database:
        disabled: false
        schedule: "0 0 * * *"
        useOwnerReferencesInBackup: false
        paused: false
        template:
          includedNamespaces:
          - database
          includedResources:
          - pvc
          - pv
