apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:NgoZG303vCamImH7BjQGMvFDy7m3GIzq3QNuZNW35Bj4zWTa,iv:+FUTGZmPArtR1SRTQNwbceYKskpUNbk8EydWkglMDZw=,tag:QrWJM/9QJ2DtbjqGcct/dg==,type:str]
    credentials.json: ENC[AES256_GCM,data:iIq5AX59JrILCsz72pojmHo8CIidtiQgXzV2gkGX/ly2hrURU1uaA1nvHb9HXiwadIxZFwkoXfULf9baxp/pExPBRrKM0/IihEi14vEey2FaeR9iAXFDgVH0tIKfnB1+dhdTGM9YSf4Y5BrdDxu6oB+EXs4kCV6MxqlVmiWKWgy3z9yvAZWLrY8MGruJ7MFzimgP5TlKln7a+ajB94OdPXb55bTVrBVNt2aIwm7xVw==,iv:hReIpHwIf8i/q9NGkMVAEzI71TqrZ55HADB7wBXWtMQ=,tag:8w0V/+tVmxZWsJhK6pUDRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdU94eUxjdVZvaTZZNmRh
            TnZybXhIMXhmTzNETmw2WXFOcThWTmNnNTI0CnJWU3ZQRXJxdVc0aE5OVXVUZmw4
            Z2p6bHg1ZGJpWitoUVlwYVFWWkg0d0UKLS0tIFpKcVQzbXQ1WXJzSUMrT2JnLzY4
            ZURYVyt2ZlVQWnhLWkJ4elorQ1czZDAKO71plbfec+z0GTzZMq77Mw7IeFpVFLTW
            Rzih+r3ObVkj5l9PAwv4QT+biJjvnw+5Q0Ggi7FK+BluNdZDEwPzvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:47:01Z"
    mac: ENC[AES256_GCM,data:ZVRUGuYh9lGrGyu70VDkt/m61SwtkgqSuESxbdcEZQJoAvkqymogI0Frv1tRSiFq5PcFq2+19vgNzRqPrR08z5SecVfcxMSL5ay/0631L4ilZlqByBH9Kfy2/yuJFCNtTW8AfR8KfKlXEXfPTgKWLm97N9eOUDZTHy7ZdJuECVQ=,iv:KP2jC2BDVQY5+k9ktO1cjmSRtmeqPB9IhUla/RA57w8=,tag:Eu6DsPQxXJIn0QOFD+0eNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
