apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6qdNRd5Xe7b7dquIaWMzZSRLEsEmcY946kByoAuUSRgZxCUhd0RKAw==,iv:41RuM/C0/sv8iza2l8WSlNAIrnQDTccujysaiZcFHlY=,tag:M7OzIjaHuOa+Ru11ZqiYCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dHRNS085cmZ0NC9WTGdy
            QUJTZnoya3RSWnNaSllSUkRtWUExTVkreEVjCldWUlFHZkJpSnh1aTFmN1VoMUFJ
            d054QnJrc3NTaEMyZU9OcFhHMlZCRlUKLS0tIHVqRWxmNFZqNm0yNjdaZTJxbEtF
            eVlTNUdFd0pHejd6UnBUOThsOHU2SE0Kft8EO08uOVyl5eGQ/mIVKItPuM1FswuN
            7nKS96wMLyyB02FEWbk7yUTVLkIndymWOVjbXn49ExMusRPUTAK/OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:55:15Z"
    mac: ENC[AES256_GCM,data:XFSuj0jcQyp8LEIih6el4Nt1S4dmxVS9Xb3lO6sbfBeNoocLA/cUbAbFvq2TSWakq3Us/vIIpUZlr3X7PwPQ/pP7QcYa5OpNcjraJpLqPEM5VR3L2V/zSDtsyzC50Ja/G0c+EgRifBv92RoPglOB/VErc1iTjcbCW8lsM/XnnuQ=,iv:0TcQX+EfctNQ1nTX68VKaen8OrvtIoEQLrzPfZY3WbY=,tag:YC2azKoaubA5SYg0/0fqwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
