---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mayastor
spec:
  interval: 30m
  chart:
    spec:
      chart: mayastor
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
