apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:nzVJyKmjohFajR6gdb2O7B+GCHhISSTgcnTL0jPqmS4KAPpzgTxcRj6cR0Nwhy5FFxb7B4UDLyc7UgL6YlEupz2wVA4Z1eOnmg/eCOzs0tiWxGGy3nK95Tvr56t18g==,iv:pMaKBXvVEIdzGX4YypFbPOi3F7b5InOwqYLDovqCwpc=,tag:i58ZeScMdAAwMAvNkvxS+A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:xV7vWcSF,iv:vLWj2+pSjASTiSlk89TV06gVKS9YRCg2rv67q5JOfhM=,tag:CSqCE4lD4CLSzZ6g6jNCBw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4gVqrGaW6z25joCt9UwxfwPg4g==,iv:vn5M9rsHinuz7KBNMufRsPi6XVgzq+hUrNomC45fuck=,tag:Rdjzr9r73fU4WXUZlUUA+w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pEDk4HcZq4850ln2xb/iWum0LEmlzkurFO6kJQKHcV0/m2pp,iv:mA9Q/uQFZwgpqQlxQLq62vptKvdH2xHszmAJQiiLMEw=,tag:jIwReWMf4gqDTjcUUB+PJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWTl1QnlqeHJQZnNCYWQ0
            eG45K25PN1B6dSs5ZGZaNGNLSUZoZjA3Nmk0CnVTUm1wK0xiQ0RvZkw2dm0zODhj
            ZUdxVVd4Z0RMbm43S2sxUjlkZ3M4dlUKLS0tIHpXN09GaS91UGpPNnRMbnBFdTVn
            bzlXNUhtbkJEekxVSHRPZjROUlVNVnMK6T+Yitx12IjAhoKdq8Dcee2wxC2Nh+ug
            scGlT0UuJ7cLbLDNP7elAKLuy6uG5FapFxEgbxxkOmZh6sGfPMKNBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:55:15Z"
    mac: ENC[AES256_GCM,data:tMnDPXp0ygQGu4Gp/+5faqD4AS381m/coOrC0jl+06ijvVnJt+7zvn3hXeB35whlJvctDRT1zoaR63lVFPvfGoaZ/d0oRrXtoJcMQKyB2QW5r57uXb7GOt+VEnVLMYcHeWKOITKleUMr7c+mJLogqwnf5we5hzC5c9FRgp3sQFc=,iv:5Lpc7Sj7kPizrs/PDAOFFr0SbKHY4c1Kvrvacb1T+D0=,tag:1H7MLnkD+qLjnl39+wRTvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
