apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:P+9px/xCYiYt/BEeGMXgenJo9qVepCbmd9NHTounMlLwLmiMU7EDYdzXa6GvmVV9739O5zb2R1QiIG4GocDgL1qDKcTeV73vQY+aCIvjLc/xYZ81bHELCYw1NbtJ+A==,iv:k7gxkT2JOO/MqUWBzN5/TBExusBVA0JkVu8X5O+8z9E=,tag:IEqECcOedSs+PJDtT6FGOw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ix9ocU7P,iv:R7kRrSj6WXOdemHsYyOEA3BQ4SqUjwt5Fhdj+Ii+B9k=,tag:0tsLxWtzjLOPFJ0BaSXDaA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sxVnDk9tyV3UCwypNUjrngTTgg==,iv:gN88LZyP00qbfnSHlocu8BXRpgQdNOMbJ78POZTNEyA=,tag:79U4SygNdAyhaAgymAeUQg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T1+GD5qIocqKEYb84T0F1CVUoAzr14nZScyPUYLaeInrQk+n,iv:HjtkKc8zFYagsOJ6kv1kuO/lTTbdw1oMXkQV0VP6UDA=,tag:mJ6EVgjUulh0pEsm+wKVWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYmxTWWpWZUo1OE5JSUZu
            dGU1ZWdhY244R0hhWC9pYXp6c24xR2hnOW5RCjUxM1F1eFNuZVpveWhmdmNMU0dD
            S1hpd0NTeUhnQzh4RStiNmRTejg3czQKLS0tIFUzU3BvN1dtR0dUOHQvc1crWkxn
            U0J3ek1OZWppc2VBb01NZ2tQTFNEbUkKkXs87ucZUWVTmCtm15rhs92dRQBVkx3c
            F+kpobqJryQUDGQLlC23mfvGLaBp0R0vQHHOHVR/BDHii6/5Cj1DNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T06:15:58Z"
    mac: ENC[AES256_GCM,data:ue+wvFLA50JQ6hb+mMcTNhhcyMzqwXFvCdRAcC650ngi2f12L5BM2HICPvH1CZnixPb+l0AB6zf0zP/P2H4YM/TAMhhis+w9xAF6yiD/RuNLMIlUoc0BtV0f3qkn0ZnQrIbbYF7nSOGS/8NTVYHr8qL35vVw7nHCKflqwJ2DOaE=,iv:rruo64iyQs2yEQQOdhx2fL67RdONrctU7fXOZZrvJmI=,tag:9i2ji77fcQUWZYFuKpVYnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
