---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
spec:
  interval: 30m
  chart:
    spec:
      chart: plex-media-server
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    image:
      repository: plexinc/pms-docker
      # renovate: datasource=docker depName=docker.io/plexinc/pms-docker
      tag: 1.40.3.8555-fef15d30c
    ingress:
      enabled: true
      ingressClassName: external
      url: plex.${SECRET_DOMAIN}
      annotations:
        external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    service:
      type: LoadBalancer
      port: 32400
      annotations:
        io.cilium/lb-ipam-ips: 192.168.4.5
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    extraEnv:
      TZ: Europe/Zurich
      ADVERTISE_IP: https://plex.${SECRET_DOMAIN}:443,http://192.168.4.5:32400
      ALLOWED_NETWORKS: 192.168.0.0/16
      PLEX_UID: "1002"
      PLEX_GID: "1002"
    pms:
      configExistingClaim: plex
      resources:
        requests:
          cpu: 100m
        limits:
          gpu.intel.com/i915: 1
          memory: 8Gi
    extraVolumeMounts:
      - name: media
        mountPath: /media
      - name: cache
        mountPath: /config/Library/Application Support/Plex Media Server/Cache
      - name: logs
        mountPath: /config/Library/Application Support/Plex Media Server/Logs
    extraVolumes:
      - name: media
        nfs:
          server: 192.168.1.5
          path: /storage/media
          readOnly: true
      - name: cache
        persistentVolumeClaim:
          claimName: plex-cache
      - name: logs
        emptyDir: {}
