---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ring2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ring2mqtt-secret
    template:
      engineVersion: v2
      config.json: |
        {
            "mqtt_url": "mqtt://localhost:1883",
            "mqtt_options": "",
            "livestream_user": "",
            "livestream_pass": "",
            "disarm_code": "",
            "enable_cameras": true,
            "enable_modes": false,
            "enable_panic": false,
            "hass_topic": "homeassistant/status",
            "ring_topic": "ring",
            "location_ids": []
        }
      ring-state.json: ${RING2MQTT_RING_STATE_JSON}
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: ring2mqtt
