apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:f4MBAvz7Cowr1SJ+DXE5gp/7ASqYQ9Q7sH6glMQwOfk=,iv:E58jG320iRzXkt4/2kHMumacDtMsRLJHMLCc7MkOyBg=,tag:ZRXVHNKtYY06vrtj+yTaPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUTFhcUswajhpU2Y4RFNt
            VFJTb2Y1dEJmc0IyUVRITitKMUJPTXFZNDNBCkpYN0lQc0N2MDYxZGplWXBrQkhH
            QVlJUEFrRWJMb2l0Z0Z5SG83MXBKcXMKLS0tIExNNnFWdUpBZW5QY2RPNVhRTmxS
            MVpReENLZWp1cXJJSkh4a1ZUdFFnRmsK672WFls8CXZORV1DVCW2aBusZSCL2iR/
            fWstEpYM6/19zYtNBjAFXpEkOJXBh2gNOfxCY/tvs5+008bYY4SdvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-24T11:32:03Z"
    mac: ENC[AES256_GCM,data:NaM6XwWgVRLQo+6Eq30aBtKGR5GyDkNaIWsx5DYqvuSAEbB7g0mDpzMHzCol3JRHWPz0cX0GKVkMEm/tn++9L32XNE5SCJqAO+7Chyz6bK0+ukRppTZea6L/1/gnumYCr/NgTVacYpZ5DHi9au+YyUACCf3WEpSadb4d0v85ZGg=,iv:s+KanmHs9Q44gKJHLdOrz18TkpLc/9aY8z6gE9lDGkw=,tag:uPYILNNgm2TNh/N8zHmQOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
