apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:DJ7kbP/GftRk8HTb+gv/DcqIPndmlnx0sCg8LHP7qBk=,iv:m08viOwX79m/B0K6zo2SsIQiWuYwUfYc03s3BLDHn3c=,tag:tJuaXUBkvWWFqrBKoFYGXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNEo4U09oV2dTMzdycGVi
            MWhicU1VcTZrM09UbWRxcm5iY3BGNHduWjBrCmZGelVjREdXaGx2VkpBNEx2ajAx
            SkJQT2JudkhaSUZmbFNmaG9TM2tTZ1kKLS0tIEtOWTgrU3JlaFZZZ0M4TkZaR1Ir
            R202QUVZY1BWUHVUd21lNmRPeHNWMlkKwAZWw0usiZJvwahicOG7YbvI4ACWXrjX
            pcOcCQuMLdgT27edWyfXvGnh0bCbLFmb9pa3MAilHXuuxRo7XReXjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:55:15Z"
    mac: ENC[AES256_GCM,data:T+1/gbooJcJueL/xZdH6r8+tcvMKe5T2SExtH8o/EuDUkgG9uhGsefJZRON19ihdLOQoiC3hlPkOpGTajcZBU+Piv0MUeOJC8WbJ15Lj/F9bvRx34+kucyOM+pN8hkdmZJH9AeQQKIXEV2PMf/+t3PKUNeiKjnv+wr3rpG+3UD4=,iv:l+OTHalfyahn/jtfvAFxZuLRFOkm/2ZChfb1XrFAW1c=,tag:4gEMBfv0r4nQRyj9a2evCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
