apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:1GoxoVANN/c/I1dSFBvtPfsgnkiWbX25JLCETothG5k=,iv:f9CozKLEBjpfLuWXWPluE74L+AEETG4V38bWCLr1yRY=,tag:esixqN4O5V90F447QSckeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdkJWTU9LSXl5MmdEcGZm
            M1ZPSVhMcldGZDR3VU1HcmhzVGtsZW1vL2trClRTQWdsQklRTXRrWnpMaTY3TVEv
            N0F1eGdKZTFibkJzcUdBaTJVZUVuZjgKLS0tIDZmTTJuMXp0VGk3V2w4OVJkWlZV
            V2w0eEw5TG53dUhva0xIeDdDdWFDRTQKYzYpiDoxseO3L3nIJrLwYpGKO27cGEym
            UYfVzy0S8fUkXc8aLFdYKCRX3EoqNM+EvoDrv5UPhBleukBzOCdNIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:37:08Z"
    mac: ENC[AES256_GCM,data:qZ/LybJujETfr9uJe6rcOJ7uFAApfOwXwwcFobwF18DKT62jQZ/ucu2fnZA7rUffKhffDPbX8Exsf3akyV/ZeoLwUI42rJuGHNjdB9BzYkiA+SdfPCijjDhC+yWgG3aE/Voa68DW4efrumDeUgaRStVBYRseANKoFzxkqOPOfkU=,iv:xqi4r6YXvXK+odSvYGTO8OPsZ92zvnO9n9t3J2vviFo=,tag:U86N1/cHAE1mNhD/dJ0BdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
