apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:FzMEBsG8L58euoJmsuxTFw8nisxYlfSy34y1L1cX7JA=,iv:ZxffgjTw+tkUBLzZZEr6sLUmQ5s8Ibuagc59gPw/vH0=,tag:lh4iqW15UtGARfjxs7nbog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uedhk2ag9rksp9qxnrsfzm3dnkdfw2y5f56p7y7e9cztzczchpnsup9ksk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcmpUQS8rclQ3WnpTUW9W
            KzBYaVE2cGhSR0pkNnNGV0FLVkdGREMzT1VBCmNCWnl6K0UyNzJRSm9iM3ZoWmpS
            SFpQQzIyTmJZWnAxNmxQNG1rWWwyV2MKLS0tIE1FQXNKek82TnJ6VkVVNjhxWFhX
            M0xOai9BOW1qd3U4cXJPTzZCZmxJVjgKhSvIyaRMsxErkKGP4A2wEuuEaet32RQQ
            rVxrT9l4U9luBE5/0Bjbsk318KloaGzbQsw9dG1wKI2cCZ3XV1/WSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-24T11:41:12Z"
    mac: ENC[AES256_GCM,data:JT7Nd8y4xClOddc+8qHaUFLBcTg2YGdV5sHm9jOtqSVseg+sqeOfJAyBp2XVSdSq0/5emLwqZ2nUchN/W2LtIUevMb211QZcSCdAthKQPzCBL+MOB3ELw0MLJ2KpNeNH1WFEKa0q8zzijnBSAAI65yeQR/zNPdEBOiLT5SRpxuI=,iv:YXpgKns8Dpo1JMU+7AxV4BkLL8UGpGC9Cv4Jn4g2OVc=,tag:YpfY7h2Td0m4Dg0w60ZzZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
