---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.4
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
